// ═══════════════════════════════════════════════════════════════
// CARWISE — Demonstration Mock Data (Phase 2 Visual Baseline)
// Clearly marked as simulated demo data, not real AI predictions
// ═══════════════════════════════════════════════════════════════

import { CARWISEInspectionReport } from './types';

export const DEMO_INSPECTIONS: CARWISEInspectionReport[] = [
  {
    id: 'demo-insp-2026-001',
    isDemonstrationData: true,
    inspectionDate: '2026-08-22T10:30:00Z',
    status: 'COMPLETED',
    vehicleInfo: {
      make: 'Honda',
      model: 'City',
      variant: 'ZX 1.5 i-VTEC',
      year: 2021,
      fuelType: 'petrol',
      transmission: 'manual',
      mileageKm: 42500,
      askingPrice: 890000,
      currency: 'INR',
      location: 'Bengaluru, Karnataka',
      vinOrReg: 'KA01MJ4921',
    },
    conditionScore: {
      overallScore: 78,
      observableCosmeticScore: 82,
      panelIntegrityScore: 76,
      paintIntegrityScore: 75,
      deductionSummary: [
        { finding: 'Surface scratch on left front door panel', zone: 'ZONE_LEFT_SIDE', deduction: 4 },
        { finding: 'Moderate bumper scuff and slight gap variance', zone: 'ZONE_FRONT_RIGHT', deduction: 10 },
        { finding: 'Minor paint chip near boot lid edge', zone: 'ZONE_REAR', deduction: 3 },
        { finding: 'Minor dent on right rear fender', zone: 'ZONE_REAR_RIGHT', deduction: 5 },
      ],
    },
    evidenceConfidence: {
      visualCoverageIndex: 0.85,
      mandatoryAnglesSubmitted: 4,
      optionalAnglesSubmitted: 5,
      uninspectedBlindspots: [
        'Underbody / chassis not photographed',
        'Engine bay detailed view omitted',
        'Left rear tyre sidewall unverified',
      ],
      dataCompletenessRatio: 0.90,
    },
    trustScore: {
      overallTrustScore: 76,
      trustBand: 'MODERATE_CONFIDENCE',
      confidenceSummary: 'Good visual coverage across all 4 mandatory angles. Moderate confidence in overall assessment.',
      limitations: [
        'Assessment is based solely on submitted 2D photographs.',
        'Engine bay and mechanical internals were not photographed.',
        'Requires hands-on physical verification and OBD diagnostic scan.',
      ],
    },
    detections: [
      {
        _id: 'det-1',
        imageAngle: 'front',
        vehicleZone: 'ZONE_FRONT_RIGHT',
        damageType: 'dent',
        component: 'Front Bumper Right Section',
        severity: 'moderate',
        confidence: 0.88,
        bbox: { x: 0.65, y: 0.58, w: 0.18, h: 0.14 },
        notes: 'Visible deformation along lower right bumper curve.',
      },
      {
        _id: 'det-2',
        imageAngle: 'front-right',
        vehicleZone: 'ZONE_FRONT_RIGHT',
        damageType: 'panel_misalignment',
        component: 'Right Front Fender Gap',
        severity: 'minor',
        confidence: 0.82,
        bbox: { x: 0.42, y: 0.38, w: 0.12, h: 0.22 },
        notes: 'Gap irregularity between bumper and fender joint.',
      },
      {
        _id: 'det-3',
        imageAngle: 'left',
        vehicleZone: 'ZONE_LEFT_SIDE',
        damageType: 'scratch',
        component: 'Front Left Door Lower Panel',
        severity: 'minor',
        confidence: 0.91,
        bbox: { x: 0.35, y: 0.62, w: 0.25, h: 0.05 },
        notes: 'Clearcoat surface scratch approximately 18cm long.',
      },
      {
        _id: 'det-4',
        imageAngle: 'rear',
        vehicleZone: 'ZONE_REAR',
        damageType: 'paint_anomaly',
        component: 'Boot Lid Lower Edge',
        severity: 'minor',
        confidence: 0.79,
        bbox: { x: 0.48, y: 0.72, w: 0.08, h: 0.06 },
        notes: 'Small paint flaking near registration plate housing.',
      },
    ],
    crossViewObservations: [
      {
        vehicleZone: 'ZONE_FRONT_RIGHT',
        zoneTitle: 'Front-Right Quarter Zone',
        involvedViews: ['front', 'front-right'],
        observedFinding: 'Co-located bumper deformation and adjacent fender joint misalignment observed across front and front-right angles.',
        confidenceIndicator: 'HIGH',
        recommendedAction: 'Inspect right front inner fender apron and mounting clips with a paint depth gauge for possible prior repair.',
      },
    ],
    priceValuation: {
      status: 'PENDING_DATASET_VALIDATION',
      datasetName: 'Indian Used Car Regional Valuation Model (In Progress)',
      fairRangeLow: 830000,
      fairRangeHigh: 910000,
      fairMedian: 870000,
      askingPrice: 890000,
      priceDeltaPercentage: 2.3,
      valuationNote: 'Asking price is aligned within the estimated regional bracket for a 2021 Honda City ZX with 42,500 km. Final valuation model pending regional dataset validation.',
    },
    prioritizedChecklist: [
      {
        id: 'chk-1',
        priority: 'HIGH',
        zone: 'ZONE_FRONT_RIGHT',
        item: 'Right Front Apron & Panel Gap',
        rationale: 'Verify whether the front-right bumper and fender misalignment is due to minor clip dislodgement or previous impact.',
      },
      {
        id: 'chk-2',
        priority: 'MEDIUM',
        zone: 'ZONE_LEFT_SIDE',
        item: 'Door Panel Paint Depth Check',
        rationale: 'Check if surface scratch on left door has penetrated primer or caused under-surface oxidation.',
      },
      {
        id: 'chk-3',
        priority: 'LOW',
        zone: 'ZONE_REAR',
        item: 'Boot Lid Seal & Latch Alignment',
        rationale: 'Check weather sealing around boot lid paint chip.',
      },
    ],
    finalRecommendation: {
      verdict: 'RECOMMENDED_FOR_INSPECTION',
      summaryHeading: 'Consider & Proceed to Hands-On Inspection',
      summaryText: 'Vehicle exhibits sound overall cosmetic condition (Condition Score 78/100) with solid visual evidence completeness (85%). Focus your physical inspection on the front-right bumper/fender joint and verify service logs before finalizing purchase.',
    },
  },
  {
    id: 'demo-insp-2026-002',
    isDemonstrationData: true,
    inspectionDate: '2026-08-21T15:45:00Z',
    status: 'COMPLETED',
    vehicleInfo: {
      make: 'Hyundai',
      model: 'Creta',
      variant: 'SX (O) 1.5 Diesel',
      year: 2019,
      fuelType: 'diesel',
      transmission: 'automatic',
      mileageKm: 68000,
      askingPrice: 1180000,
      currency: 'INR',
      location: 'Hyderabad, Telangana',
      vinOrReg: 'TS09UB8172',
    },
    conditionScore: {
      overallScore: 64,
      observableCosmeticScore: 68,
      panelIntegrityScore: 60,
      paintIntegrityScore: 65,
      deductionSummary: [
        { finding: 'Multiple scratches across right side doors', zone: 'ZONE_RIGHT_SIDE', deduction: 8 },
        { finding: 'Severe dent on tailgate lower corner', zone: 'ZONE_REAR', deduction: 16 },
        { finding: 'Paint color mismatch between hood and front bumper', zone: 'ZONE_FRONT', deduction: 12 },
      ],
    },
    evidenceConfidence: {
      visualCoverageIndex: 0.62,
      mandatoryAnglesSubmitted: 3, // Missing Left side view
      optionalAnglesSubmitted: 2,
      uninspectedBlindspots: [
        'Left side profile completely missing (Mandatory angle omitted)',
        'Dashboard & odometer not photographed',
        'Interior cabin condition unverified',
      ],
      dataCompletenessRatio: 0.70,
    },
    trustScore: {
      overallTrustScore: 48,
      trustBand: 'INSUFFICIENT_EVIDENCE',
      confidenceSummary: 'Assessment is capped due to missing mandatory Left-side angle and detected multi-panel paint variations.',
      limitations: [
        'Left-side vehicle body was not photographed. High visual blindspot risk.',
        'Odometer reading could not be visually confirmed from dashboard photo.',
        'Requires immediate physical verification of omitted panels.',
      ],
    },
    detections: [
      {
        _id: 'det-5',
        imageAngle: 'rear',
        vehicleZone: 'ZONE_REAR',
        damageType: 'dent',
        component: 'Tailgate Lower Right Section',
        severity: 'severe',
        confidence: 0.94,
        bbox: { x: 0.55, y: 0.62, w: 0.22, h: 0.20 },
        notes: 'Deep indentation with paint creasing on lower tailgate.',
      },
      {
        _id: 'det-6',
        imageAngle: 'front',
        vehicleZone: 'ZONE_FRONT',
        damageType: 'paint_anomaly',
        component: 'Front Hood vs Bumper',
        severity: 'moderate',
        confidence: 0.81,
        bbox: { x: 0.30, y: 0.20, w: 0.40, h: 0.35 },
        notes: 'Visible shade variance suggesting possible partial panel repaint.',
      },
    ],
    crossViewObservations: [
      {
        vehicleZone: 'ZONE_REAR',
        zoneTitle: 'Rear Body & Tailgate Zone',
        involvedViews: ['rear', 'rear-right'],
        observedFinding: 'Severe tailgate dent co-located near rear bumper reinforcement zone.',
        confidenceIndicator: 'HIGH',
        recommendedAction: 'Check rear hatch floorpan, spare wheel well, and tailgate latch for impact distortion.',
      },
    ],
    priceValuation: {
      status: 'PENDING_DATASET_VALIDATION',
      datasetName: 'Indian Used Car Regional Valuation Model (In Progress)',
      fairRangeLow: 980000,
      fairRangeHigh: 1060000,
      fairMedian: 1020000,
      askingPrice: 1180000,
      priceDeltaPercentage: 15.7,
      valuationNote: 'Asking price is substantially higher than typical fair-market baseline given observed cosmetic flaws and missing visual evidence.',
    },
    prioritizedChecklist: [
      {
        id: 'chk-4',
        priority: 'HIGH',
        zone: 'ZONE_LEFT_SIDE',
        item: 'Entire Left Profile Physical Inspection',
        rationale: 'Mandatory left side photo was omitted from upload. Check both doors, quarter panel, and pillars.',
      },
      {
        id: 'chk-5',
        priority: 'HIGH',
        zone: 'ZONE_REAR',
        item: 'Spare Wheel Well & Rear Floor Pan',
        rationale: 'Ensure the severe tailgate impact did not distort the rear crash structure.',
      },
    ],
    finalRecommendation: {
      verdict: 'HIGH_RISK_AVOID',
      summaryHeading: 'Proceed With Caution / Demand Full Evidence',
      summaryText: 'Low Trust Score (48/100) due to omitted mandatory left side photo and significant rear body damage. Do not place a deposit before a full in-person inspection and test drive.',
    },
  },
];
